services:
  api:
    build: .
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DATABASE_URL: "sqlite:///./test.db"
      OLLAMA_API_URL: "http://host.docker.internal:11434"  # This allows container to access host's Ollama
