apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-hello-world
  template:
    metadata:
      labels:
        app: fastapi-hello-world
    spec:
      containers:
      - name: fastapi-hello-world
        image: fastapi-hello-world:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
